GRANT ALL PRIVILEGES ON EMPRUNT TO AGACHE;
GRANT ALL PRIVILEGES ON ETUDIANT TO AGACHE;
GRANT ALL PRIVILEGES ON EXEMPLAIRE TO AGACHE;
GRANT ALL PRIVILEGES ON LIVRE TO AGACHE;
GRANT ALL PRIVILEGES ON RESERV TO AGACHE;

REVOKE ALL PRIVILEGES ON EMPRUNT FROM AGACHE;
REVOKE ALL PRIVILEGES ON ETUDIANT FROM AGACHE;
REVOKE ALL PRIVILEGES ON EXEMPLAIRE FROM AGACHE;
REVOKE ALL PRIVILEGES ON LIVRE FROM AGACHE;
REVOKE ALL PRIVILEGES ON RESERV FROM AGACHE;