/*
Script de création de la base de donnée de la bibliothèque de l'IUT de Velizy
*/
DROP TABLE ETUDIANT CASCADE CONSTRAINTS;
DROP TABLE LIVRE CASCADE CONSTRAINTS;
DROP TABLE EXEMPLAIRE CASCADE CONSTRAINTS;
DROP TABLE EMPRUNT CASCADE CONSTRAINTS;
DROP TABLE RESERV CASCADE CONSTRAINTS;

CREATE TABLE ETUDIANT(
id_et INT PRIMARY KEY NOT NULL,
nom varchar(20) NOT NULL,
prenom varchar(20) NOT NULL,
email varchar(80) UNIQUE NOT NULL,
mdp varchar(20) NOT NULL);

CREATE TABLE LIVRE(
id_livre INT PRIMARY KEY NOT NULL,
titre varchar(80),
auteur varchar(50));

CREATE TABLE EXEMPLAIRE(
id_ex INT PRIMARY KEY NOT NULL,
id_livre INT REFERENCES LIVRE(id_livre));

CREATE TABLE EMPRUNT(
id_et INT REFERENCES ETUDIANT(id_et),
id_ex INT REFERENCES EXEMPLAIRE(id_ex) UNIQUE,
date_emp DATE NOT NULL,
date_retour DATE NOT NULL);

CREATE TABLE RESERV (
id_livre INT REFERENCES LIVRE(id_livre),
id_et INT REFERENCES ETUDIANT(id_et),
date_res DATE NOT NULL,
date_fin_res DATE NOT NULL);


--CLES PRIMAIRE
ALTER TABLE ETUDIANT ADD CONSTRAINT PK_ETUDIANT PRIMARY KEY (ID_ET);
ALTER TABLE EXEMPLAIRE ADD CONSTRAINT PK_EXEMPLAIRE PRIMARY KEY (ID_EX);
ALTER TABLE LIVRE ADD CONSTRAINT PK_LIVRE PRIMARY KEY (ID_LIVRE);

--CLES ETRANGERES
ALTER TABLE EXEMPLAIRE ADD CONSTRAINT FK_EXEMPLAIRE_ID_LIVRE FOREIGN KEY(ID_LIVRE) REFERENCES LIVRE(ID_LIVRE);
ALTER TABLE EMPRUNT ADD CONSTRAINT FK_EMPRUNT_ID_ETUDIANT FOREIGN KEY(ID_ET) REFERENCES ETUDIANT(ID_ET);
ALTER TABLE EMPRUNT ADD CONSTRAINT FK_EMPRUNT_ID_EXEMPLAIRE FOREIGN KEY(ID_EX) REFERENCES EXEMPLAIRE(ID_EX);
ALTER TABLE RESERV ADD CONSTRAINT FK_RESERV_ID_ET FOREIGN KEY(ID_ET) REFERENCES ETUDIANT(ID_ET);
ALTER TABLE RESERV ADD CONSTRAINT FK_RESERV_ID_LIVRE FOREIGN KEY(ID_LIVRE) REFERENCES LIVRE(ID_LIVRE);